### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by meton-robean** [domainexpert/trip-counter#1]
hi, when i compile your project, i get the following error:

clang++ `llvm-config --cxxflags` -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0  `llvm-config --ldflags`  TripCounter.cpp  `llvm-config --libs` -lpthread -lncurses -ldl -o TripCounter
/bin/sh: 1: llvm-config: not found
/bin/sh: 1: llvm-config: not found
/bin/sh: 1: llvm-config: not found
TripCounter.cpp:12:10: fatal error: 'llvm/InitializePasses.h' file not found
#include "llvm/InitializePasses.h"
         ^
1 error generated.
<builtin>: recipe for target 'TripCounter' failed
make: *** [TripCounter] Error 1

can you help me figure it out?

**Comment by domainexpert** [comment]
@meton-robean What happens if you simply run `make`?
Also, this was developed using LLVM 3.4.2. If you are using a later version, that may not be backward compatible.

**Comment by domainexpert** [comment]
@meton-robean Closing this issue now. Please feel free to re-open if you still need help.
